### PR TITLE
could be prettier, but retain options

### PR DESCRIPTION
**Pull request by RobertLowe**
fixes for:

 = form.input :start_at, :as => :date_picker, :input_html => {:class => "unicorns"}

### CODE REVIEW

**Comment by demersus** [comment]
Robert, is your commit basically allowing the merge of multiple classes through the options?  Is there anything else I should be aware of?  I did a brief glance at the code, but my brain is tired because of the daylight savings time change.

**Comment by RobertLowe** [comment]
Yes, anything passed with options is merged properly, 

`= form.input :start_at, :as => :date_picker, :input_html => {:class => "unicorns", :data-message => 'hello world'}`

would render the input correctly with

`....  class="ui-date-picker unicorns" data-message="hello world" ....`

same fix is applied to datetime for wrapper_html / input_html

and yes, daylight savings are killing me too, sorry i didnt have time to make tests its late! :(

**Comment by demersus** [comment]
Ok, I pulled your commit into a project that I have been using the date picker in.  Without adding any options for the ':input_html'  key,  I am experiencing an exception with this message:

```
You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]
```

It does not specify the line in the plugin causing the error, but does specify it is related to this line of code in my view:
    = f.input :beginning, :as => :datetime_picker

I like what you are trying to accomplish here. I think I need to see some tests to make sure it is working properly, before I will pull your commit into the master branch.

Thanks for your hard work, and ideas.

**Comment by RobertLowe** [comment]
Sorry, I missed a line! My copying and pasting at late hours is to blame.

`options[:input_html] ||= {}`

Forced pushed an update, everything is sunshine and rainbows

**Comment by demersus** [comment]
Ok, so now I am getting this error:  `undefined method 'gsub' for nil:NilClass`

Same code as before.  I did not add the :input_html option key.  Just default settings.

I don't see any call to gsub in the plugin code.    Looking at the full trace, it is happening here:
    activesupport (3.0.4) lib/active_support/whiny_nil.rb:48:in `method_missing'
    activesupport (3.0.4) lib/active_support/time_with_zone.rb:171:in`strftime'
    vendor/plugins/formtastic_datepicker_inputs/lib/formtastic_datepicker_inputs.rb:54:in `datetime_picker_options'
    vendor/plugins/formtastic_datepicker_inputs/lib/formtastic_datepicker_inputs.rb:41:in`datetime_picker_input'

I am not sure why, if I change back to my master branch, I do not get this error message.

**Pull request closed without merging**
